### PR TITLE
Fixing combineURLs to support an empty relativeURL

### LINKED ISSUE #574: API endpoints with file extensions
Hello! Great project.

To jump right in, it is a hacky experience to create an axios client for a single-endpoint API that also uses a file extension. ie `https://coolapi.com/api.php`

All url requests make their way through `combineURLs.js`, to be appended with a `/` regardless of if there was a relative url attached to the client's request config.

The current hack (it feels like hack...) to get around this is to add a request interceptor to remove the ending slash. I'm currently doing this in a project.

Happy to PR this issue with a fix to combineURLs - but I want to run it past owners first for validity.

Cheers! ✨

### PR DESCRIPTION
**Pull request by loklaan**
Ending slashes were always being appended to the baseURL, regardless of if the relative URL had length.

By making sure that we're supporting empty relative urls, and not appending extraneous slashes to the base url, support for absolute API endpoints becomes possible.

Added a single test spec. 📈 

Closes #574

### CODE REVIEW

File: lib/helpers/combineURLs.js [hunk 1]
```diff
@@ -8,5 +8,8 @@
  * @returns {string} The combined URL
  */
 module.exports = function combineURLs(baseURL, relativeURL) {
-  return baseURL.replace(/\/+$/, '') + '/' + relativeURL.replace(/^\/+/, '');
+  var end = relativeURL.replace(/^\/+/, '');
```
Comment (nickuraltsev) [inline lib/helpers/combineURLs.js]: If `relativeURL` is `'/'`, it will not be added, right? For example:

```js
combineURLs('http://test.com/foo', '/'); // => 'http://test.com/foo'
```

I would suggest to append `relativeURL` unless it's falsy (`''`, `undefined`, `null`). Thoughts?

Comment (loklaan) [inline lib/helpers/combineURLs.js]: I thought about this, and covered the case by using the full baseURL (it could include an ending slash).

```js
combineURLs('http://test.com/foo/', ''); // => 'http://test.com/foo/'
```

But yes I think it may be confusing without the support for your suggestion.

Comment (nickuraltsev) [inline lib/helpers/combineURLs.js]: Cool, could you please update the PR?

**Comment by loklaan** [comment]
Hey @nickuraltsev, this should be good to go now! Squashing the commits on merge would be good.

**Comment by nickuraltsev** [comment]
@loklaan Thanks a lot for the contribution!

**Comment by loklaan** [comment]
Thanks for the help! Hope to contribute more via #520. :)

**Comment by TylerBrock** [comment]
Can you do a release for this one? It's a very common use case.
